<div class="jumbotron device-info-jumbotron" style="width:100%">
	<div class="container">
		<center>
			<h1><?php echo $DEVICE_NAME; ?><br /><small><?php echo $DEVICE_DESC; ?></small></h1>
			
			<br />
						
			<form action="index.php" method="post" name="main">
				<div class="row">
					<div class="col-md-3"></div>
					<label class="col-md-2">Username:</label>
					<input class="col-md-4" id="username" name="username" placeholder="username" type="text" tabindex="1">
				</div> <!-- /.row -->
				
				<div class="row">
					<div class="col-md-3"></div>
					<label class="col-md-2">Password:</label>
					<input class="col-md-4" id="password" name="password" placeholder="********" type="password" tabindex="2">
				</div> <!-- /.row -->

				<br />
				
				<div class="row">
					<button type="submit button" class="btn btn-success glyphicon glyphicon-log-in" id="<?php echo $LOGIN_BTN ?>" name="<?php echo $LOGIN_BTN ?>" value="<?php echo $LOGIN_BTN ?>" tabindex="3" data-toggle="tooltip" title="Login"></button>
				</div> <!-- /.row -->
			</form>
			<div class="row">
				<div class="col-xs-12">
					<?php echo $error_msg; ?> <!-- Error generated by login.php -->
				</div>
			</div>
		</center>
	</div><!-- /.container -->
</div><!-- /.jumbotron -->
